/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/airplane.glb -o src/components/AirplaneModel.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    leftwing: THREE.Mesh
    rightwing: THREE.Mesh
    leftback: THREE.Mesh
    body: THREE.Mesh
    rightback: THREE.Mesh
    top: THREE.Mesh
  }
  materials: {
    ['LineH_krilo02-FACES_COLOR_0_COLOR_0.001']: THREE.MeshStandardMaterial
    ['Ellipse10-FACES_COLOR_0_COLOR_0.001']: THREE.MeshStandardMaterial
    ['Object03-FACES_1_COLOR_0_COLOR_0.001']: THREE.MeshStandardMaterial
    ['Ellipse09-FACES_COLOR_0_COLOR_0.001']: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/airplane.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.leftwing.geometry} material={materials['LineH_krilo02-FACES_COLOR_0_COLOR_0.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.rightwing.geometry} material={materials['LineH_krilo02-FACES_COLOR_0_COLOR_0.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.leftback.geometry} material={materials['Ellipse10-FACES_COLOR_0_COLOR_0.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.body.geometry} material={materials['Object03-FACES_1_COLOR_0_COLOR_0.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.rightback.geometry} material={materials['Ellipse10-FACES_COLOR_0_COLOR_0.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.top.geometry} material={materials['Ellipse09-FACES_COLOR_0_COLOR_0.001']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/airplane.glb')
